# Generated by Django 5.0.14 on 2026-01-14 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('osoby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sektor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, verbose_name='Sektor / Kwatera')),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sektor cmentarza',
                'verbose_name_plural': 'Sektory cmentarza',
            },
        ),
        migrations.CreateModel(
            name='Grob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rzad', models.CharField(blank=True, max_length=5, verbose_name='Rząd')),
                ('numer', models.CharField(max_length=5, verbose_name='Numer grobu')),
                ('typ', models.CharField(choices=[('ZIEMNY_1', 'Ziemny pojedynczy'), ('ZIEMNY_2', 'Ziemny podwójny'), ('MUROWANY_1', 'Murowany pojedynczy'), ('MUROWANY_2', 'Murowany rodzinny'), ('URNOWY', 'Urnowy'), ('DZIECIECY', 'Dziecięcy')], default='ZIEMNY_1', max_length=30, verbose_name='Typ grobu')),
                ('data_oplaty', models.DateField(default=django.utils.timezone.now, verbose_name='Data wniesienia opłaty')),
                ('wazny_do', models.DateField(blank=True, null=True, verbose_name='Ważny do (Prolongata)')),
                ('uwagi', models.TextField(blank=True)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='cmentarz/nagrobki/', verbose_name='Zdjęcie nagrobka')),
                ('dysponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groby_dysponowane', to='osoby.osoba', verbose_name='Dysponent (Opiekun)')),
                ('sektor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groby', to='cmentarz.sektor', verbose_name='Sektor')),
            ],
            options={
                'verbose_name': 'Grób',
                'verbose_name_plural': 'Groby',
                'ordering': ['sektor', 'numer'],
                'unique_together': {('sektor', 'rzad', 'numer')},
            },
        ),
        migrations.CreateModel(
            name='Pochowany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pochowania', models.DateField(default=django.utils.timezone.now, verbose_name='Data pogrzebu')),
                ('grob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pochowani', to='cmentarz.grob')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miejsce_spoczynku', to='osoby.osoba', verbose_name='Osoba zmarła')),
            ],
            options={
                'verbose_name': 'Osoba pochowana',
                'verbose_name_plural': 'Osoby pochowane',
                'ordering': ['-data_pochowania'],
            },
        ),
    ]
