# Generated by Django 5.0.14 on 2025-12-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sektor', models.CharField(max_length=10, verbose_name='Sektor')),
                ('rzad', models.CharField(max_length=10, verbose_name='Rząd')),
                ('numer', models.CharField(max_length=10, verbose_name='Numer grobu')),
                ('rodzaj', models.CharField(choices=[('POJ', 'Pojedynczy'), ('ROD', 'Rodzinny'), ('URNA', 'Grób na urnę')], default='POJ', max_length=10, verbose_name='Rodzaj grobu')),
                ('data_wygasniecia_dzierzawy', models.DateField(blank=True, help_text='Jeśli puste – brak informacji lub dzierżawa bezterminowa.', null=True, verbose_name='Data wygaśnięcia dzierżawy')),
                ('uwagi', models.TextField(blank=True, help_text='Np. nazwisko opiekuna grobu, informacje dodatkowe.', verbose_name='Uwagi')),
                ('aktywny', models.BooleanField(default=True, help_text='Odznacz, jeśli grób jest zlikwidowany / nieużywany.', verbose_name='Aktywny grób')),
            ],
            options={
                'verbose_name': 'Grób',
                'verbose_name_plural': 'Groby',
                'ordering': ['sektor', 'rzad', 'numer'],
                'unique_together': {('sektor', 'rzad', 'numer')},
            },
        ),
    ]
