# Generated by Django 5.0.14 on 2025-12-01 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmentarz', '0001_initial'),
        ('osoby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sektor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, verbose_name='Sektor / Kwatera')),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sektor cmentarza',
                'verbose_name_plural': 'Sektory cmentarza',
            },
        ),
        migrations.AlterModelOptions(
            name='grob',
            options={'ordering': ['sektor', 'numer'], 'verbose_name': 'Grób', 'verbose_name_plural': 'Groby'},
        ),
        migrations.AddField(
            model_name='grob',
            name='data_oplaty',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data wniesienia opłaty'),
        ),
        migrations.AddField(
            model_name='grob',
            name='dysponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groby_dysponowane', to='osoby.osoba', verbose_name='Dysponent (Opiekun)'),
        ),
        migrations.AddField(
            model_name='grob',
            name='typ',
            field=models.CharField(choices=[('ZIEMNY_1', 'Ziemny pojedynczy'), ('ZIEMNY_2', 'Ziemny podwójny'), ('MUROWANY_1', 'Murowany pojedynczy'), ('MUROWANY_2', 'Murowany rodzinny'), ('URNOWY', 'Urnowy'), ('DZIECIECY', 'Dziecięcy')], default='ZIEMNY_1', max_length=20, verbose_name='Typ grobu'),
        ),
        migrations.AddField(
            model_name='grob',
            name='wazny_do',
            field=models.DateField(blank=True, null=True, verbose_name='Ważny do (Prolongata)'),
        ),
        migrations.AddField(
            model_name='grob',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='cmentarz/nagrobki/', verbose_name='Zdjęcie nagrobka'),
        ),
        migrations.AlterField(
            model_name='grob',
            name='numer',
            field=models.CharField(max_length=20, verbose_name='Numer grobu'),
        ),
        migrations.AlterField(
            model_name='grob',
            name='rzad',
            field=models.CharField(blank=True, max_length=20, verbose_name='Rząd'),
        ),
        migrations.AlterField(
            model_name='grob',
            name='uwagi',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Pochowany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pochowania', models.DateField(default=django.utils.timezone.now, verbose_name='Data pogrzebu')),
                ('grob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pochowani', to='cmentarz.grob')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miejsce_spoczynku', to='osoby.osoba', verbose_name='Osoba zmarła')),
            ],
            options={
                'verbose_name': 'Osoba pochowana',
                'verbose_name_plural': 'Osoby pochowane',
                'ordering': ['-data_pochowania'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='grob',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='grob',
            name='sektor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groby', to='cmentarz.sektor', verbose_name='Sektor'),
        ),
        migrations.AlterUniqueTogether(
            name='grob',
            unique_together={('sektor', 'numer')},
        ),
        migrations.RemoveField(
            model_name='grob',
            name='aktywny',
        ),
        migrations.RemoveField(
            model_name='grob',
            name='data_wygasniecia_dzierzawy',
        ),
        migrations.RemoveField(
            model_name='grob',
            name='rodzaj',
        ),
    ]
