# Generated by Django 5.0.14 on 2026-01-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmentarz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grob',
            name='numer',
            field=models.CharField(max_length=4, verbose_name='Numer grobu'),
        ),
        migrations.AlterField(
            model_name='grob',
            name='rzad',
            field=models.CharField(blank=True, max_length=4, verbose_name='Rząd'),
        ),
    ]
