# Generated by Django 5.0.14 on 2025-12-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmentarz', '0002_sektor_alter_grob_options_grob_data_oplaty_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grob',
            unique_together={('sektor', 'numer', 'rzad')},
        ),
    ]
