# Generated by Django 5.0.14 on 2025-12-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmentarz', '0003_alter_grob_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grob',
            unique_together={('sektor', 'rzad', 'numer')},
        ),
    ]
