# Generated by Django 5.0.14 on 2025-12-03 22:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupUstawienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wlaczony', models.BooleanField(default=False, verbose_name='Włącz automatyczne backupy')),
                ('czestotliwosc', models.CharField(choices=[('dziennie', 'Raz dziennie'), ('tygodniowo', 'Raz w tygodniu'), ('miesiecznie', 'Raz w miesiącu')], default='dziennie', max_length=20, verbose_name='Częstotliwość')),
                ('dzien_tygodnia', models.IntegerField(blank=True, choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')], null=True, verbose_name='Dzień tygodnia (dla backupu tygodniowego)')),
                ('godzina', models.TimeField(default=datetime.time(2, 0), verbose_name='Godzina uruchamiania')),
            ],
            options={
                'verbose_name': 'Ustawienia backupu',
                'verbose_name_plural': 'Ustawienia backupu',
            },
        ),
        migrations.CreateModel(
            name='LogAkcji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiedy', models.DateTimeField(auto_now_add=True, verbose_name='Data i czas')),
                ('akcja', models.CharField(max_length=50, verbose_name='Akcja')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('obiekt_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID obiektu')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('uzytkownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logi', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Log akcji',
                'verbose_name_plural': 'Logi akcji',
                'ordering': ['-kiedy'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rola', models.CharField(choices=[('ADMIN', 'Administrator'), ('KSIAZD', 'Ksiądz'), ('SEKRET', 'Sekretariat')], default='SEKRET', max_length=20)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
