# Generated by Django 5.0.14 on 2025-11-30 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAkcji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiedy', models.DateTimeField(auto_now_add=True, verbose_name='Data i czas')),
                ('akcja', models.CharField(max_length=50, verbose_name='Akcja')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('obiekt_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID obiektu')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('uzytkownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logi', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Log akcji',
                'verbose_name_plural': 'Logi akcji',
                'ordering': ['-kiedy'],
            },
        ),
    ]
