# Generated by Django 5.0.14 on 2025-12-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupustawienia',
            name='ostatni_backup',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ostatni wykonany backup'),
        ),
    ]
