# Generated by Django 5.0.14 on 2026-01-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0002_backupustawienia_ostatni_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='rola',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('KSIADZ', 'Ksiądz'), ('SEKRET', 'Sekretariat')], default='SEKRET', max_length=20),
        ),
    ]
