# Generated by Django 5.0.14 on 2025-11-30 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0002_logakcji'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupUstawienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czestotliwosc', models.CharField(choices=[('never', 'Tylko ręcznie'), ('daily', 'Codziennie'), ('weekly', 'Raz w tygodniu'), ('monthly', 'Raz w miesiącu')], default='daily', max_length=20, verbose_name='Częstotliwość backupu')),
                ('godzina', models.TimeField(default=datetime.time(2, 0), help_text='Godzina, o której ma być wykonywany backup.', verbose_name='Godzina uruchamiania')),
                ('ostatni_backup', models.DateTimeField(blank=True, help_text='Uzupełniane automatycznie przez mechanizm backupu.', null=True, verbose_name='Ostatnio wykonany backup')),
                ('włączony', models.BooleanField(default=True, verbose_name='Włącz automatyczne backupy')),
            ],
            options={
                'verbose_name': 'Ustawienia backupu',
                'verbose_name_plural': 'Ustawienia backupu',
            },
        ),
    ]
