# Generated by Django 5.0.14 on 2025-11-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0003_backupustawienia'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupustawienia',
            name='dzien_tygodnia',
            field=models.CharField(choices=[('mon', 'Poniedziałek'), ('tue', 'Wtorek'), ('wed', 'Środa'), ('thu', 'Czwartek'), ('fri', 'Piątek'), ('sat', 'Sobota'), ('sun', 'Niedziela')], default='mon', help_text="Używane, gdy częstotliwość ustawiona jest na 'Raz w tygodniu'.", max_length=3, verbose_name='Dzień tygodnia (dla backupu tygodniowego)'),
        ),
    ]
