# Generated by Django 5.0.14 on 2025-12-02 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0004_backupustawienia_dzien_tygodnia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupustawienia',
            name='włączony',
        ),
        migrations.AddField(
            model_name='backupustawienia',
            name='wlaczony',
            field=models.BooleanField(default=False, verbose_name='Włącz automatyczne backupy'),
        ),
        migrations.AlterField(
            model_name='backupustawienia',
            name='czestotliwosc',
            field=models.CharField(choices=[('daily', 'Raz dziennie'), ('weekly', 'Raz w tygodniu')], default='daily', max_length=16, verbose_name='Częstotliwość'),
        ),
        migrations.AlterField(
            model_name='backupustawienia',
            name='dzien_tygodnia',
            field=models.IntegerField(blank=True, choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')], null=True, verbose_name='Dzień tygodnia (dla backupu tygodniowego)'),
        ),
        migrations.AlterField(
            model_name='backupustawienia',
            name='godzina',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Godzina uruchamiania'),
        ),
        migrations.AlterField(
            model_name='backupustawienia',
            name='ostatni_backup',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ostatnio wykonany backup'),
        ),
    ]
