# Generated by Django 5.0.14 on 2025-12-02 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0005_remove_backupustawienia_włączony_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupustawienia',
            name='ostatni_backup',
        ),
        migrations.AlterField(
            model_name='backupustawienia',
            name='czestotliwosc',
            field=models.CharField(choices=[('dziennie', 'Raz dziennie'), ('tygodniowo', 'Raz w tygodniu'), ('miesiecznie', 'Raz w miesiącu')], default='dziennie', max_length=20, verbose_name='Częstotliwość'),
        ),
        migrations.AlterField(
            model_name='backupustawienia',
            name='godzina',
            field=models.TimeField(default=datetime.time(2, 0), verbose_name='Godzina uruchamiania'),
        ),
    ]
