# Generated by Django 5.0.14 on 2026-01-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='imie_bierzmowanie',
            field=models.CharField(blank=True, help_text='Imię przyjęte przy bierzmowaniu (jeśli dotyczy).', max_length=30, verbose_name='Imię z bierzmowania'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='imie_drugie',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='imie_matki',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='imie_ojca',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='imie_pierwsze',
            field=models.CharField(max_length=30, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='kod_pocztowy',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='miejsce_urodzenia',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='miejscowosc',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='nazwisko',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='nazwisko_matki',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nazwisko matki (aktualne)'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='nazwisko_matki_rodowe',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nazwisko rodowe matki'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='nazwisko_ojca',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nazwisko ojca'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='nazwisko_rodowe',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='nr_domu',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='nr_mieszkania',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='poczta',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='telefon',
            field=models.CharField(blank=True, max_length=415),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='ulica',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
