# Generated by Django 5.0.14 on 2025-11-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wyznanie',
        ),
    ]
