# Generated by Django 5.0.14 on 2025-11-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='imie_bierzmowania',
            field=models.CharField(blank=True, help_text='Imię przyjęte przy bierzmowaniu (jeśli dotyczy).', max_length=120, verbose_name='Imię z bierzmowania'),
        ),
    ]
