# Generated by Django 5.0.14 on 2025-11-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0002_osoba_imie_bierzmowania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='wyznanie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osoby', to='osoby.wyznanie', verbose_name='Wyznanie'),
        ),
    ]
