# Generated by Django 5.0.14 on 2025-11-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0003_alter_osoba_wyznanie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osoba',
            old_name='imie_bierzmowania',
            new_name='imie_bierzmowanie',
        ),
    ]
