# Generated by Django 5.0.14 on 2025-11-02 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0004_rename_imie_bierzmowania_osoba_imie_bierzmowanie'),
        ('slowniki', '0004_wyznanie_aktywne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='wyznanie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osoby', to='slowniki.wyznanie', verbose_name='Wyznanie'),
        ),
    ]
