# Generated by Django 5.0.14 on 2025-11-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0005_alter_osoba_wyznanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='nazwisko_matki',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nazwisko matki (aktualne)'),
        ),
        migrations.AddField(
            model_name='osoba',
            name='nazwisko_matki_rodowe',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nazwisko rodowe matki'),
        ),
        migrations.AddField(
            model_name='osoba',
            name='nazwisko_ojca',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nazwisko ojca'),
        ),
    ]
