# Generated by Django 5.0.14 on 2025-11-16 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data mszy')),
                ('godzina', models.TimeField(verbose_name='Godzina mszy')),
                ('miejsce', models.CharField(help_text='Np. Kościół parafialny / Kaplica / Kościół filialny', max_length=120, verbose_name='Miejsce')),
                ('celebrans', models.CharField(blank=True, help_text='Kto odprawia (opcjonalnie)', max_length=120, verbose_name='Celebrans')),
                ('uwagi', models.TextField(blank=True, help_text='Np. zmiana celebransa, uwagi organizacyjne', verbose_name='Uwagi (wewnętrzne)')),
            ],
            options={
                'verbose_name': 'Msza',
                'verbose_name_plural': 'Msze',
                'ordering': ['data', 'godzina', 'miejsce'],
                'indexes': [models.Index(fields=['data'], name='msze_msza_data_f2cf5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntencjaMszy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField(help_text='Np. "+ Jan Kowalski od żony i dzieci"', verbose_name='Treść intencji')),
                ('zamawiajacy', models.CharField(blank=True, help_text='Np. Rodzina Kowalskich', max_length=200, verbose_name='Zamawiający / od kogo')),
                ('ofiara', models.CharField(blank=True, help_text='Kwota / dar (tylko do użytku kancelarii)', max_length=120, verbose_name='Ofiara')),
                ('uwagi', models.TextField(blank=True, help_text="Np. 'zarezerwowano telefonicznie'", verbose_name='Uwagi wewnętrzne')),
                ('msza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intencje', to='msze.msza', verbose_name='Msza')),
            ],
            options={
                'verbose_name': 'Intencja mszalna',
                'verbose_name_plural': 'Intencje mszalne',
                'ordering': ['msza', 'pk'],
            },
        ),
    ]
