# Generated by Django 5.0.14 on 2025-12-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msza',
            name='typ',
            field=models.CharField(choices=[('POWSZEDNIA', 'Powszednia'), ('NIEDZIELNA', 'Niedzielna'), ('SLUBNA', 'Ślubna'), ('POGRZEBOWA', 'Pogrzebowa'), ('ODPUSTOWA', 'Odpustowa'), ('SWIATECZNA', 'Świateczna'), ('GREGORIANSKA', 'Gregoriańska'), ('ZBIOROWA', 'Zbiorowa (wiele intencji)'), ('JUBILEUSZOWA', 'Jubileuszowa (rocznice)'), ('RORATNIA', 'Roratnia')], default='POWSZEDNIA', max_length=20, verbose_name='Rodzaj mszy'),
        ),
    ]
