# Generated by Django 5.0.14 on 2025-12-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msze', '0002_alter_msza_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intencjamszy',
            name='tresc',
            field=models.TextField(help_text='Np. "+ Jan Kowalski od żony i dzieci".', verbose_name='Treść intencji'),
        ),
        migrations.AlterField(
            model_name='intencjamszy',
            name='uwagi',
            field=models.TextField(blank=True, help_text="Np. 'zarezerwowano telefonicznie'.", verbose_name='Uwagi wewnętrzne'),
        ),
        migrations.AlterField(
            model_name='intencjamszy',
            name='zamawiajacy',
            field=models.CharField(blank=True, help_text='Np. Rodzina Kowalskich.', max_length=200, verbose_name='Zamawiający / od kogo'),
        ),
        migrations.AlterField(
            model_name='msza',
            name='miejsce',
            field=models.CharField(help_text='Np. Kościół parafialny / Kaplica ', max_length=120, verbose_name='Miejsce'),
        ),
        migrations.AlterField(
            model_name='msza',
            name='typ',
            field=models.CharField(choices=[('POWSZEDNIA', 'Powszednia'), ('NIEDZIELNA', 'Niedzielna'), ('SLUBNA', 'Ślubna'), ('POGRZEBOWA', 'Pogrzebowa'), ('ODPUSTOWA', 'Odpustowa'), ('SWIATECZNA', 'Świąteczna'), ('GREGORIANSKA', 'Gregoriańska'), ('ZBIOROWA', 'Zbiorowa (wiele intencji)'), ('JUBILEUSZOWA', 'Jubileuszowa (rocznice)'), ('RORATNIA', 'Roratnia')], default='POWSZEDNIA', max_length=20, verbose_name='Rodzaj mszy'),
        ),
        migrations.AlterField(
            model_name='msza',
            name='uwagi',
            field=models.TextField(blank=True, help_text='Np. zmiana celebransa, uwagi organizacyjne.', verbose_name='Uwagi (wewnętrzne)'),
        ),
    ]
