# Generated by Django 5.0.14 on 2026-01-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msze', '0003_alter_intencjamszy_tresc_alter_intencjamszy_uwagi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msza',
            name='celebrans_opis',
            field=models.CharField(blank=True, help_text='Wypełnij tylko jeśli celebransa nie ma na liście powyżej.', max_length=30, verbose_name='Celebrans (opis ręczny)'),
        ),
    ]
