# Generated by Django 5.0.14 on 2025-12-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msze', '0003_alter_msza_typ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intencjamszy',
            name='ofiara',
        ),
        migrations.AddField(
            model_name='intencjamszy',
            name='status_oplaty',
            field=models.CharField(choices=[('NIEOPLACONA', 'Nieopłacona'), ('OPLACONA', 'Opłacona')], default='NIEOPLACONA', max_length=12, verbose_name='Status opłaty'),
        ),
    ]
