# Generated by Django 5.0.14 on 2025-11-30 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('osoby', '0001_initial'),
        ('slowniki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodzina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('ulica', models.CharField(blank=True, max_length=120)),
                ('nr_domu', models.CharField(blank=True, max_length=30)),
                ('nr_mieszkania', models.CharField(blank=True, max_length=30)),
                ('kod_pocztowy', models.CharField(blank=True, max_length=15)),
                ('miejscowosc', models.CharField(blank=True, max_length=120)),
                ('poczta', models.CharField(blank=True, max_length=120)),
                ('telefon_kontaktowy', models.CharField(blank=True, max_length=40)),
                ('email_kontaktowy', models.EmailField(blank=True, max_length=254)),
                ('uwagi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rodzina / kartoteka',
                'verbose_name_plural': 'Rodziny / kartoteki',
                'ordering': ['miejscowosc', 'ulica', 'nr_domu', 'nr_mieszkania', 'nazwa'],
                'indexes': [models.Index(fields=['miejscowosc', 'ulica', 'nr_domu'], name='rodziny_rod_miejsco_a8462f_idx')],
            },
        ),
        migrations.CreateModel(
            name='CzlonkostwoRodziny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rola', models.CharField(choices=[('MAZ', 'Mąż'), ('ZONA', 'Żona'), ('DZIECKO', 'Dziecko'), ('INNA', 'Inna rola')], default='INNA', max_length=20)),
                ('status', models.CharField(choices=[('MIESZKA', 'Mieszka'), ('WYPROW', 'Wyprowadził(a) się'), ('ZMARL', 'Zmarł(a)')], default='MIESZKA', max_length=20, verbose_name='Status zamieszkania')),
                ('uwagi', models.TextField(blank=True)),
                ('osoba', models.ForeignKey(help_text='Osoba przypisana do tej rodziny', on_delete=django.db.models.deletion.CASCADE, related_name='przynaleznosci_rodzinne', to='osoby.osoba')),
                ('rodzina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='czlonkowie', to='rodziny.rodzina')),
            ],
            options={
                'verbose_name': 'Członek rodziny',
                'verbose_name_plural': 'Członkowie rodziny',
                'ordering': ['rola', 'osoba__nazwisko', 'osoba__imie_pierwsze'],
            },
        ),
        migrations.CreateModel(
            name='WizytaDuszpasterska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.IntegerField(verbose_name='Rok wizyty')),
                ('data_wizyty', models.DateField(blank=True, null=True, verbose_name='Data wizyty')),
                ('status', models.CharField(choices=[('PRZYJETA', 'Wizyta przyjęta'), ('NIEOBECNI', 'Nieobecni / Zamknięte'), ('ODMOWA', 'Odmowa przyjęcia'), ('INNE', 'Inne')], default='PRZYJETA', max_length=20, verbose_name='Status')),
                ('ofiara', models.CharField(blank=True, help_text='Opcjonalnie', max_length=100, verbose_name='Ofiara')),
                ('notatka', models.TextField(blank=True, verbose_name='Notatki duszpasterskie')),
                ('ksiadz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slowniki.duchowny', verbose_name='Ksiądz odwiedzający')),
                ('rodzina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizyty', to='rodziny.rodzina', verbose_name='Rodzina')),
            ],
            options={
                'verbose_name': 'Wizyta duszpasterska',
                'verbose_name_plural': 'Wizyty duszpasterskie',
                'ordering': ['-rok', '-data_wizyty'],
            },
        ),
    ]
