# Generated by Django 5.0.14 on 2025-11-02 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0002_osoba_imie_bierzmowania'),
        ('rodziny', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czlonkostworodziny',
            name='osoba',
            field=models.ForeignKey(help_text='Osoba przypisana do tej rodziny', on_delete=django.db.models.deletion.CASCADE, related_name='przynaleznosci_rodzinne', to='osoby.osoba'),
        ),
        migrations.AlterField(
            model_name='czlonkostworodziny',
            name='rola',
            field=models.CharField(choices=[('MAZ', 'Mąż'), ('ZONA', 'Żona'), ('DZIECKO', 'Dziecko'), ('INNA', 'Inna rola')], default='INNA', max_length=20),
        ),
    ]
