# Generated by Django 5.0.14 on 2025-11-19 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodziny', '0001_initial'),
        ('slowniki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WizytaDuszpasterska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.IntegerField(verbose_name='Rok wizyty')),
                ('data_wizyty', models.DateField(blank=True, null=True, verbose_name='Data wizyty')),
                ('status', models.CharField(choices=[('PRZYJETA', 'Wizyta przyjęta'), ('NIEOBECNI', 'Nieobecni / Zamknięte'), ('ODMOWA', 'Odmowa przyjęcia'), ('INNE', 'Inne')], default='PRZYJETA', max_length=20, verbose_name='Status')),
                ('ofiara', models.CharField(blank=True, help_text='Opcjonalnie', max_length=100, verbose_name='Ofiara')),
                ('notatka', models.TextField(blank=True, verbose_name='Notatki duszpasterskie')),
                ('ksiadz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slowniki.duchowny', verbose_name='Ksiądz odwiedzający')),
                ('rodzina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizyty', to='rodziny.rodzina', verbose_name='Rodzina')),
            ],
            options={
                'verbose_name': 'Wizyta duszpasterska',
                'verbose_name_plural': 'Wizyty duszpasterskie',
                'ordering': ['-rok', '-data_wizyty'],
            },
        ),
    ]
