# Generated by Django 5.0.14 on 2025-11-30 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0001_initial'),
        ('rodziny', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='czlonkostworodziny',
            unique_together={('rodzina', 'osoba')},
        ),
    ]
