# Generated by Django 5.0.14 on 2026-01-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodziny', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodzina',
            name='kod_pocztowy',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='rodzina',
            name='miejscowosc',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='rodzina',
            name='nazwa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rodzina',
            name='nr_domu',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='rodzina',
            name='nr_mieszkania',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='rodzina',
            name='poczta',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='rodzina',
            name='telefon_kontaktowy',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='rodzina',
            name='ulica',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='wizytaduszpasterska',
            name='ofiara',
            field=models.CharField(blank=True, help_text='Opcjonalnie', max_length=30, verbose_name='Ofiara'),
        ),
    ]
