# Generated by Django 5.0.14 on 2025-11-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodziny', '0002_alter_czlonkostworodziny_osoba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czlonkostworodziny',
            name='status',
            field=models.CharField(choices=[('MIESZKA', 'Mieszka'), ('WYPROW', 'Wyprowadził(a) się'), ('ZMARL', 'Zmarł(a)')], default='MIESZKA', max_length=20, verbose_name='Status zamieszkania'),
        ),
        migrations.AlterField(
            model_name='rodzina',
            name='nazwa',
            field=models.CharField(max_length=200),
        ),
    ]
