# Generated by Django 5.0.14 on 2026-01-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UstawieniaParafii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='', max_length=100, verbose_name='Nazwa Parafii (nagłówek)')),
                ('miejscowosc', models.CharField(default='', max_length=50, verbose_name='Miejscowość')),
                ('adres', models.CharField(default='', max_length=80, verbose_name='Adres (ulica i kod)')),
                ('nip', models.CharField(blank=True, max_length=11, null=True, verbose_name='NIP')),
                ('regon', models.CharField(blank=True, max_length=10, null=True, verbose_name='REGON')),
                ('konto_bankowe', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nr konta bankowego')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='konfiguracja/logo/', verbose_name='Logo / Pieczęć (do wydruków)')),
            ],
            options={
                'verbose_name': 'Konfiguracja Parafii',
                'verbose_name_plural': 'Konfiguracja Parafii',
            },
        ),
    ]
