# Generated by Django 5.0.14 on 2026-01-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfiguracja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ustawieniaparafii',
            name='adres',
            field=models.CharField(default='', max_length=30, verbose_name='Adres (ulica i kod)'),
        ),
        migrations.AlterField(
            model_name='ustawieniaparafii',
            name='konto_bankowe',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nr konta bankowego'),
        ),
        migrations.AlterField(
            model_name='ustawieniaparafii',
            name='miejscowosc',
            field=models.CharField(default='', max_length=30, verbose_name='Miejscowość'),
        ),
        migrations.AlterField(
            model_name='ustawieniaparafii',
            name='nazwa',
            field=models.CharField(default='', max_length=100, verbose_name='Nazwa Parafii (nagłówek)'),
        ),
        migrations.AlterField(
            model_name='ustawieniaparafii',
            name='nip',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='ustawieniaparafii',
            name='regon',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='REGON'),
        ),
    ]
