# Generated by Django 5.0.14 on 2026-01-09 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parafia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text='Np. Parafia św. Jana Chrzciciela', max_length=80, verbose_name='Nazwa parafii')),
                ('miejscowosc', models.CharField(blank=True, max_length=50, verbose_name='Miejscowość')),
                ('diecezja', models.CharField(blank=True, max_length=50, verbose_name='Diecezja')),
                ('ulica', models.CharField(blank=True, max_length=50, verbose_name='Ulica')),
                ('nr_domu', models.CharField(blank=True, max_length=5, verbose_name='Nr domu')),
                ('nr_mieszkania', models.CharField(blank=True, max_length=5, verbose_name='Nr mieszkania')),
                ('kod_pocztowy', models.CharField(blank=True, max_length=8, verbose_name='Kod pocztowy')),
                ('poczta', models.CharField(blank=True, max_length=30, verbose_name='Poczta')),
                ('telefon', models.CharField(blank=True, max_length=15, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('uwagi', models.TextField(blank=True, help_text='Np. dekanat, status, uwagi własne', verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'Parafia',
                'verbose_name_plural': 'Parafie',
                'ordering': ['miejscowosc', 'nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Wyznanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text='Np. "rzymskokatolickie", "prawosławne", "ewangelickie", "brak"', max_length=50, unique=True, verbose_name='Nazwa wyznania')),
                ('aktywne', models.BooleanField(default=True, help_text='Jeśli odznaczone, nie pokazuje się przy dodawaniu nowych osób.', verbose_name='Aktywne')),
            ],
            options={
                'verbose_name': 'Wyznanie',
                'verbose_name_plural': 'Wyznania',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Duchowny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(blank=True, choices=[('ks.', 'ks.'), ('bisk.', 'bisk.'), ('prob.', 'prob.'), ('wik.', 'wik.'), ('dziek.', 'dziek.'), ('abp.', 'abp.'), ('kard.', 'kard.'), ('pap.', 'pap.')], help_text='Np. ks., biskp, prob.', max_length=20, verbose_name='Tytuł')),
                ('imie_nazwisko', models.CharField(help_text='Np. Jan Kowalski', max_length=30, verbose_name='Imię i nazwisko')),
                ('aktywny', models.BooleanField(default=True, help_text='Odznacz jeśli już nie posługuje, ale chcesz go mieć do historii', verbose_name='Aktywny')),
                ('uwagi', models.TextField(blank=True, help_text='Np. proboszcz, wikariusz, biskup pomocniczy', verbose_name='Uwagi')),
                ('parafia', models.ForeignKey(blank=True, help_text='Parafia, w której posługiwał przy sakramencie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duchowni', to='slowniki.parafia', verbose_name='Parafia posługi')),
            ],
            options={
                'verbose_name': 'Duchowny',
                'verbose_name_plural': 'Duchowni',
                'ordering': ['imie_nazwisko'],
            },
        ),
    ]
