# Generated by Django 5.0.14 on 2025-11-02 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parafia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text='Np. Parafia św. Jana Chrzciciela', max_length=200, verbose_name='Nazwa parafii')),
                ('miejscowosc', models.CharField(blank=True, max_length=120, verbose_name='Miejscowość')),
                ('diecezja', models.CharField(blank=True, max_length=120, verbose_name='Diecezja')),
                ('uwagi', models.TextField(blank=True, help_text='Np. dekanat, status, uwagi własne', verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'Parafia',
                'verbose_name_plural': 'Parafie',
                'ordering': ['miejscowosc', 'nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Wyznanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text='Np. "rzymskokatolickie", "prawosławne", "ewangelickie", "brak"', max_length=200, unique=True, verbose_name='Wyznanie')),
                ('aktywne', models.BooleanField(default=True, help_text='Odznacz jeśli nie chcesz już pokazywać tego w nowych formularzach', verbose_name='Aktywne')),
            ],
            options={
                'verbose_name': 'Wyznanie',
                'verbose_name_plural': 'Wyznania',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Duchowny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(blank=True, choices=[('ks.', 'ks.'), ('ks. bp', 'ks. bp'), ('dk.', 'dk.'), ('o.', 'o.'), ('br.', 'br.')], help_text='Np. ks., ks. bp, dk.', max_length=20, verbose_name='Tytuł')),
                ('imie_nazwisko', models.CharField(help_text='Np. Jan Kowalski', max_length=200, verbose_name='Imię i nazwisko')),
                ('aktywny', models.BooleanField(default=True, help_text='Odznacz jeśli już nie posługuje, ale chcesz go mieć do historii', verbose_name='Aktywny')),
                ('uwagi', models.TextField(blank=True, help_text='Np. proboszcz, wikariusz, biskup pomocniczy', verbose_name='Uwagi')),
                ('parafia', models.ForeignKey(blank=True, help_text='Parafia, w której posługiwał przy sakramencie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duchowni', to='slowniki.parafia', verbose_name='Parafia posługi')),
            ],
            options={
                'verbose_name': 'Duchowny',
                'verbose_name_plural': 'Duchowni',
                'ordering': ['imie_nazwisko'],
            },
        ),
    ]
