# Generated by Django 5.0.14 on 2025-11-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowniki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wyznanie',
            name='aktywne',
        ),
        migrations.AddField(
            model_name='parafia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='parafia',
            name='kod_pocztowy',
            field=models.CharField(blank=True, max_length=15, verbose_name='Kod pocztowy'),
        ),
        migrations.AddField(
            model_name='parafia',
            name='nr_domu',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nr domu'),
        ),
        migrations.AddField(
            model_name='parafia',
            name='nr_mieszkania',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nr mieszkania'),
        ),
        migrations.AddField(
            model_name='parafia',
            name='poczta',
            field=models.CharField(blank=True, max_length=120, verbose_name='Poczta'),
        ),
        migrations.AddField(
            model_name='parafia',
            name='telefon',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='parafia',
            name='ulica',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ulica'),
        ),
    ]
