# Generated by Django 5.0.14 on 2026-01-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowniki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duchowny',
            name='imie_nazwisko',
            field=models.CharField(help_text='Np. Jan Kowalski', max_length=30, verbose_name='Imię i nazwisko'),
        ),
        migrations.AlterField(
            model_name='parafia',
            name='diecezja',
            field=models.CharField(blank=True, max_length=30, verbose_name='Diecezja'),
        ),
        migrations.AlterField(
            model_name='parafia',
            name='kod_pocztowy',
            field=models.CharField(blank=True, max_length=8, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='parafia',
            name='miejscowosc',
            field=models.CharField(blank=True, max_length=30, verbose_name='Miejscowość'),
        ),
        migrations.AlterField(
            model_name='parafia',
            name='nazwa',
            field=models.CharField(help_text='Np. Parafia św. Jana Chrzciciela', max_length=50, verbose_name='Nazwa parafii'),
        ),
        migrations.AlterField(
            model_name='parafia',
            name='nr_domu',
            field=models.CharField(blank=True, max_length=4, verbose_name='Nr domu'),
        ),
        migrations.AlterField(
            model_name='parafia',
            name='nr_mieszkania',
            field=models.CharField(blank=True, max_length=4, verbose_name='Nr mieszkania'),
        ),
        migrations.AlterField(
            model_name='parafia',
            name='poczta',
            field=models.CharField(blank=True, max_length=30, verbose_name='Poczta'),
        ),
        migrations.AlterField(
            model_name='parafia',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='parafia',
            name='ulica',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='wyznanie',
            name='nazwa',
            field=models.CharField(help_text='Np. "rzymskokatolickie", "prawosławne", "ewangelickie", "brak"', max_length=30, unique=True, verbose_name='Nazwa wyznania'),
        ),
    ]
