# Generated by Django 5.0.14 on 2025-11-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowniki', '0002_remove_wyznanie_aktywne_parafia_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyznanie',
            name='nazwa',
            field=models.CharField(help_text='Np. "rzymskokatolickie", "prawosławne", "ewangelickie", "brak"', max_length=200, unique=True, verbose_name='Nazwa wyznania'),
        ),
    ]
