# Generated by Django 5.0.14 on 2025-11-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowniki', '0003_alter_wyznanie_nazwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyznanie',
            name='aktywne',
            field=models.BooleanField(default=True, help_text='Jeśli odznaczone, nie pokazuje się przy dodawaniu nowych osób.', verbose_name='Aktywne'),
        ),
    ]
