# Generated by Django 5.0.14 on 2025-11-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowniki', '0004_wyznanie_aktywne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duchowny',
            name='tytul',
            field=models.CharField(blank=True, choices=[('ks.', 'ks.'), ('bisk.', 'bisk.'), ('prob.', 'prob.'), ('wik.', 'wik.'), ('dziek.', 'dziek.'), ('abp.', 'abp.'), ('kard.', 'kard.'), ('pap.', 'pap.')], help_text='Np. ks., biskp, prob.', max_length=20, verbose_name='Tytuł'),
        ),
    ]
