# Generated by Django 5.0.14 on 2025-11-02 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('osoby', '0002_osoba_imie_bierzmowania'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chrzest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.PositiveIntegerField(help_text='Rok księgi chrztów (np. 2025)', verbose_name='Rok')),
                ('akt_nr', models.CharField(help_text='Numer aktu chrztu w danym roku', max_length=20, verbose_name='Nr aktu')),
                ('data_urodzenia', models.DateField(blank=True, null=True, verbose_name='Data urodzenia')),
                ('rok_urodzenia', models.PositiveIntegerField(blank=True, help_text='Wpisz tylko rok, jeśli nie znasz pełnej daty', null=True, verbose_name='Rok urodzenia (jeśli brak pełnej daty)')),
                ('miejsce_urodzenia', models.CharField(blank=True, max_length=200, verbose_name='Miejsce urodzenia')),
                ('data_chrztu', models.DateField(help_text='Pełna data chrztu', verbose_name='Data chrztu')),
                ('miejsce_chrztu', models.CharField(blank=True, help_text='Np. kościół parafialny', max_length=200, verbose_name='Miejsce chrztu')),
                ('szafarz', models.CharField(blank=True, help_text='Kapłan / diakon udzielający chrztu', max_length=200, verbose_name='Udzielił chrztu')),
                ('ojciec', models.CharField(blank=True, max_length=200, verbose_name='Ojciec')),
                ('matka', models.CharField(blank=True, max_length=200, verbose_name='Matka')),
                ('cel_wydania_swiadectwa', models.CharField(blank=True, choices=[('slub', 'Do ślubu'), ('bierzmowanie', 'Do bierzmowania'), ('inne', 'Inne'), ('', '—')], default='', help_text='Np. do ślubu albo do bierzmowania', max_length=20, verbose_name='Cel wydania świadectwa')),
                ('uwagi_kanoniczne', models.TextField(blank=True, help_text='Np. zawarł małżeństwo..., wyświęcony..., wystąpił z Kościoła...', verbose_name='Uwagi (małżeństwo / święcenia / wystąpienie z Kościoła)')),
                ('uwagi_wew', models.TextField(blank=True, verbose_name='Uwagi kancelaryjne (tylko do użytku kancelarii)')),
                ('ochrzczony', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chrzty', to='osoby.osoba', verbose_name='Ochrzczony/a')),
            ],
            options={
                'verbose_name': 'Chrzest',
                'verbose_name_plural': 'Chrzty',
                'ordering': ['-rok', 'akt_nr'],
                'indexes': [models.Index(fields=['rok'], name='sakramenty__rok_d6a118_idx'), models.Index(fields=['akt_nr'], name='sakramenty__akt_nr_84e4ac_idx')],
                'unique_together': {('rok', 'akt_nr')},
            },
        ),
    ]
