# Generated by Django 5.0.14 on 2025-12-03 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmentarz', '0001_initial'),
        ('osoby', '0001_initial'),
        ('slowniki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bierzmowanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.CharField(blank=True, help_text='Np. 2005', max_length=10, verbose_name='Rok bierzmowania')),
                ('akt_nr', models.CharField(blank=True, help_text='Numer aktu chrztu w danym roku, jeśli nie podasz, wypełni się automatycznie.', max_length=20, verbose_name='Nr aktu bierzmowania')),
                ('data_bierzmowania', models.DateField(blank=True, help_text='Pełna data (dzień-miesiąc-rok)', null=True, verbose_name='Data bierzmowania (pełna)')),
                ('imie_bierzmowania', models.CharField(blank=True, help_text='Imię przyjęte przy bierzmowaniu', max_length=100, verbose_name='Imię bierzmowania')),
                ('miejsce_bierzmowania', models.CharField(blank=True, max_length=100, verbose_name='Miejsce bierzmowania')),
                ('parafia_nazwa_reczna', models.CharField(blank=True, help_text='Jeśli nie ma na liście powyżej', max_length=200, verbose_name='Parafia (opis ręczny)')),
                ('szafarz_opis_reczny', models.CharField(blank=True, help_text='Np. «bp Jan Kowalski», «ks. Piotr Nowak»', max_length=200, verbose_name='Szafarz (opis ręczny)')),
                ('swiadek', models.CharField(blank=True, help_text='Imię i nazwisko świadka', max_length=200, verbose_name='Świadek bierzmowania')),
                ('uwagi_wew', models.TextField(blank=True, verbose_name='Uwagi kancelaryjne (wewnętrzne)')),
                ('skan_aktu', models.FileField(blank=True, null=True, upload_to='skany/bierzmowania/', verbose_name='Skan świadectwa/aktu')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bierzmowania', to='osoby.osoba', verbose_name='Osoba')),
                ('parafia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bierzmowania', to='slowniki.parafia', verbose_name='Parafia bierzmowania')),
                ('szafarz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bierzmowania_udzielone', to='slowniki.duchowny', verbose_name='Szafarz (udzielający bierzmowania)')),
            ],
            options={
                'verbose_name': 'Bierzmowanie',
                'verbose_name_plural': 'Bierzmowania',
                'ordering': ['rok', 'osoba__nazwisko', 'osoba__imie_pierwsze'],
            },
        ),
        migrations.CreateModel(
            name='Chrzest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.PositiveIntegerField(help_text='Rok księgi chrztów (np. 2025)', verbose_name='Rok')),
                ('akt_nr', models.CharField(help_text='Numer aktu chrztu w danym roku, jeśli nie podasz, wypełni się automatycznie.', max_length=20, verbose_name='Nr aktu')),
                ('data_urodzenia', models.DateField(blank=True, null=True, verbose_name='Data urodzenia')),
                ('rok_urodzenia', models.PositiveIntegerField(blank=True, help_text='Wpisz tylko rok, jeśli nie znasz dokładnej daty urodzenia', null=True, verbose_name='Rok urodzenia (jeśli brak pełnej daty)')),
                ('miejsce_urodzenia', models.CharField(blank=True, max_length=200, verbose_name='Miejsce urodzenia')),
                ('data_chrztu', models.DateField(blank=True, help_text='Pełna data (dzień-miesiąc-rok), jeśli znana', null=True, verbose_name='Data chrztu (pełna)')),
                ('rok_chrztu', models.PositiveIntegerField(blank=True, help_text='Wpisz tylko rok, jeśli nie znasz pełnej daty chrztu', null=True, verbose_name='Rok chrztu')),
                ('miejsce_chrztu', models.CharField(blank=True, max_length=200, verbose_name='Miejsce chrztu')),
                ('ojciec', models.CharField(blank=True, max_length=200, verbose_name='Ojciec (imię i nazwisko)')),
                ('matka', models.CharField(blank=True, max_length=200, verbose_name='Matka (imię i nazwisko)')),
                ('nazwisko_matki_rodowe', models.CharField(blank=True, max_length=200, verbose_name='Nazwisko rodowe matki')),
                ('uwagi_wew', models.TextField(blank=True, verbose_name='Uwagi kancelaryjne (wewnętrzne)')),
                ('skan_aktu', models.FileField(blank=True, help_text='Opcjonalnie: załącz skan aktu (PDF, JPG)', null=True, upload_to='skany/chrzty/', verbose_name='Skan aktu')),
                ('matka_wyznanie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matki_przy_chrzcie', to='slowniki.wyznanie', verbose_name='Matka - wyznanie')),
                ('ochrzczony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chrzty', to='osoby.osoba', verbose_name='Ochrzczony/a')),
                ('ojciec_wyznanie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ojcowie_przy_chrzcie', to='slowniki.wyznanie', verbose_name='Ojciec - wyznanie')),
                ('parafia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chrzty', to='slowniki.parafia', verbose_name='Parafia chrztu')),
            ],
            options={
                'verbose_name': 'Chrzest',
                'verbose_name_plural': 'Chrzty',
                'ordering': ['-rok', 'akt_nr'],
            },
        ),
        migrations.CreateModel(
            name='Malzenstwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.CharField(blank=True, help_text='Np. 2014. Możesz wpisać tylko rok.', max_length=10, verbose_name='Rok ślubu')),
                ('akt_nr', models.CharField(blank=True, help_text='Numer aktu w księdze małżeństw.', max_length=30, verbose_name='Nr aktu małżeństwa')),
                ('data_slubu', models.DateField(blank=True, help_text='Pełna data (dzień-miesiąc-rok)', null=True, verbose_name='Data ślubu (pełna)')),
                ('parafia_opis_reczny', models.CharField(blank=True, help_text='Jeśli nie ma parafii na liście powyżej, wpisz tutaj.', max_length=200, verbose_name='Parafia ślubu (opis ręczny)')),
                ('swiadek_urzedowy_opis_reczny', models.CharField(blank=True, help_text='Kapłan/diakon, który asystował przy zawarciu małżeństwa.', max_length=200, verbose_name='Świadek urzędowy / asystujący (opis ręczny)')),
                ('swiadek_a', models.CharField(blank=True, max_length=200, verbose_name='Świadek A')),
                ('swiadek_b', models.CharField(blank=True, max_length=200, verbose_name='Świadek B')),
                ('uwagi_wew', models.TextField(blank=True, verbose_name='Uwagi (wewnętrzne)')),
                ('skan_aktu', models.FileField(blank=True, null=True, upload_to='skany/malzenstwa/', verbose_name='Skan aktu/protokołu')),
                ('malzonek_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malzenstwa_jako_a', to='osoby.osoba', verbose_name='Małżonek A')),
                ('malzonek_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malzenstwa_jako_b', to='osoby.osoba', verbose_name='Małżonek B')),
                ('parafia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sluby', to='slowniki.parafia', verbose_name='Parafia ślubu')),
                ('swiadek_urzedowy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sluby_asystowane', to='slowniki.duchowny', verbose_name='Świadek urzędowy / asystujący')),
            ],
            options={
                'verbose_name': 'Małżeństwo',
                'verbose_name_plural': 'Małżeństwa',
                'ordering': ['-rok', 'malzonek_a__nazwisko', 'malzonek_b__nazwisko'],
            },
        ),
        migrations.CreateModel(
            name='NamaszczenieChorych',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data posługi')),
                ('miejsce', models.CharField(blank=True, help_text='Np. dom chorego, szpital', max_length=200, verbose_name='Miejsce')),
                ('spowiedz', models.BooleanField(default=False, verbose_name='Spowiedź')),
                ('komunia', models.BooleanField(default=False, verbose_name='Komunia święta')),
                ('namaszczenie', models.BooleanField(default=False, verbose_name='Namaszczenie chorych')),
                ('uwagi_wew', models.TextField(blank=True, verbose_name='Uwagi duszpasterskie / stan chorego')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namaszczenia', to='osoby.osoba', verbose_name='Osoba')),
                ('szafarz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='namaszczenia_udzielone', to='slowniki.duchowny', verbose_name='Szafarz')),
            ],
            options={
                'verbose_name': 'Namaszczenie chorych / posługa',
                'verbose_name_plural': 'Namaszczenia chorych / posługi',
                'ordering': ['-data', 'osoba__nazwisko', 'osoba__imie_pierwsze'],
            },
        ),
        migrations.CreateModel(
            name='PierwszaKomunia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.CharField(blank=True, help_text='Np. 1998', max_length=10, verbose_name='Rok I Komunii')),
                ('uwagi_wew', models.TextField(blank=True, verbose_name='Uwagi kancelaryjne (wewnętrzne)')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komunie', to='osoby.osoba', verbose_name='Osoba')),
                ('parafia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='komunie', to='slowniki.parafia', verbose_name='Parafia I komuni św.')),
            ],
            options={
                'verbose_name': 'I Komunia Święta',
                'verbose_name_plural': 'I Komunie Święte',
                'ordering': ['rok', 'osoba__nazwisko', 'osoba__imie_pierwsze'],
            },
        ),
        migrations.CreateModel(
            name='Zgon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.CharField(blank=True, help_text='Np. 2024', max_length=10, verbose_name='Rok zgonu / księgi')),
                ('akt_nr', models.CharField(blank=True, help_text='Numer aktu w księdze zgonów', max_length=20, verbose_name='Nr aktu zgonu')),
                ('data_zgonu', models.DateField(blank=True, null=True, verbose_name='Data zgonu')),
                ('miejsce_zgonu', models.CharField(blank=True, max_length=200, verbose_name='Miejsce zgonu')),
                ('data_pogrzebu', models.DateField(blank=True, null=True, verbose_name='Data pogrzebu')),
                ('cmentarz', models.CharField(blank=True, max_length=200, verbose_name='Cmentarz')),
                ('uwagi_wew', models.TextField(blank=True, verbose_name='Uwagi kancelaryjne (wewnętrzne)')),
                ('skan_aktu', models.FileField(blank=True, null=True, upload_to='skany/zgony/', verbose_name='Skan aktu zgonu')),
                ('grob', models.ForeignKey(blank=True, help_text='Grób, w którym pochowano zmarłego (jeśli dotyczy).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pochowki', to='cmentarz.grob', verbose_name='Grób')),
                ('osoba', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zgon', to='osoby.osoba', verbose_name='Zmarły/a')),
            ],
            options={
                'verbose_name': 'Zgon',
                'verbose_name_plural': 'Zgony',
                'ordering': ['-rok', 'akt_nr'],
            },
        ),
        migrations.AddConstraint(
            model_name='bierzmowanie',
            constraint=models.UniqueConstraint(fields=('osoba',), name='unique_bierzmowanie_per_osoba'),
        ),
        migrations.AddIndex(
            model_name='chrzest',
            index=models.Index(fields=['rok'], name='sakramenty__rok_d6a118_idx'),
        ),
        migrations.AddIndex(
            model_name='chrzest',
            index=models.Index(fields=['akt_nr'], name='sakramenty__akt_nr_84e4ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='chrzest',
            constraint=models.UniqueConstraint(fields=('ochrzczony',), name='unique_chrzest_per_osoba'),
        ),
        migrations.AddConstraint(
            model_name='chrzest',
            constraint=models.UniqueConstraint(fields=('rok', 'akt_nr'), name='unique_chrzest_rok_akt'),
        ),
        migrations.AlterUniqueTogether(
            name='chrzest',
            unique_together={('rok', 'akt_nr')},
        ),
        migrations.AddConstraint(
            model_name='malzenstwo',
            constraint=models.UniqueConstraint(fields=('rok', 'akt_nr'), name='unique_malzenstwo_rok_akt'),
        ),
        migrations.AddConstraint(
            model_name='pierwszakomunia',
            constraint=models.UniqueConstraint(fields=('osoba',), name='unique_komunia_per_osoba'),
        ),
        migrations.AddConstraint(
            model_name='zgon',
            constraint=models.UniqueConstraint(fields=('osoba',), name='unique_zgon_per_osoba'),
        ),
        migrations.AddConstraint(
            model_name='zgon',
            constraint=models.UniqueConstraint(fields=('rok', 'akt_nr'), name='unique_zgon_rok_akt'),
        ),
    ]
