# Generated by Django 5.0.14 on 2025-11-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgon',
            name='skan_aktu',
            field=models.FileField(blank=True, null=True, upload_to='skany/zgony/', verbose_name='Skan aktu zgonu'),
        ),
    ]
