# Generated by Django 5.0.14 on 2025-11-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chrzest',
            name='cel_wydania_swiadectwa',
        ),
        migrations.RemoveField(
            model_name='chrzest',
            name='uwagi_kanoniczne',
        ),
        migrations.AddField(
            model_name='chrzest',
            name='rok_chrztu',
            field=models.PositiveIntegerField(blank=True, help_text='Wpisz tylko rok, jeśli nie znasz dokładnej daty chrztu', null=True, verbose_name='Rok chrztu (jeśli brak pełnej daty)'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='data_chrztu',
            field=models.DateField(blank=True, help_text='Pełna data (dzień-miesiąc-rok), jeśli znana', null=True, verbose_name='Data chrztu (pełna)'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='rok_urodzenia',
            field=models.PositiveIntegerField(blank=True, help_text='Wpisz tylko rok, jeśli nie znasz dokładnej daty urodzenia', null=True, verbose_name='Rok urodzenia (jeśli brak pełnej daty)'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='uwagi_wew',
            field=models.TextField(blank=True, verbose_name='Uwagi kancelaryjne (wewnętrzne)'),
        ),
    ]
