# Generated by Django 5.0.14 on 2025-11-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chrzest',
            name='skan_aktu',
            field=models.FileField(blank=True, help_text='Opcjonalnie: załącz skan aktu (PDF, JPG)', null=True, upload_to='skany/chrzty/', verbose_name='Skan aktu'),
        ),
    ]
