# Generated by Django 5.0.14 on 2025-12-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bierzmowanie',
            name='akt_nr',
            field=models.CharField(blank=True, help_text='Numer aktu chrztu w danym roku, jeśli nie podasz, wypełni się automatycznie.', max_length=20, verbose_name='Nr aktu bierzmowania'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='akt_nr',
            field=models.CharField(help_text='Numer aktu chrztu w danym roku, jeśli nie podasz, wypełni się automatycznie.', max_length=20, verbose_name='Nr aktu'),
        ),
        migrations.AlterField(
            model_name='malzenstwo',
            name='data_slubu',
            field=models.DateField(blank=True, help_text='Pełna data (dzień-miesiąc-rok)', null=True, verbose_name='Data ślubu (pełna)'),
        ),
    ]
