# Generated by Django 5.0.14 on 2025-12-28 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0001_initial'),
        ('slowniki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chrzest',
            name='sakramenty__rok_d6a118_idx',
        ),
        migrations.RemoveIndex(
            model_name='chrzest',
            name='sakramenty__akt_nr_84e4ac_idx',
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='akt_nr',
            field=models.CharField(blank=True, help_text='Numer aktu bierzmowania; jeśli nie podasz, może zostać wypełniony automatycznie.', max_length=20, verbose_name='Nr aktu bierzmowania'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='data_bierzmowania',
            field=models.DateField(blank=True, help_text='Pełna data (dzień-miesiąc-rok).', null=True, verbose_name='Data bierzmowania (pełna)'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='imie_bierzmowania',
            field=models.CharField(blank=True, help_text='Imię przyjęte przy bierzmowaniu.', max_length=100, verbose_name='Imię bierzmowania'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='parafia_nazwa_reczna',
            field=models.CharField(blank=True, help_text='Jeśli nie ma na liście powyżej.', max_length=200, verbose_name='Parafia (opis ręczny)'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='rok',
            field=models.CharField(blank=True, help_text='Np. 2005.', max_length=10, verbose_name='Rok bierzmowania'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='swiadek',
            field=models.CharField(blank=True, help_text='Imię i nazwisko świadka.', max_length=200, verbose_name='Świadek bierzmowania'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='szafarz_opis_reczny',
            field=models.CharField(blank=True, help_text='Np. „bp Jan Kowalski”, „ks. Piotr Nowak”.', max_length=200, verbose_name='Szafarz (opis ręczny)'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='akt_nr',
            field=models.CharField(help_text='Numer aktu chrztu w danym roku; jeśli nie podasz, wypełni się automatycznie.', max_length=20, verbose_name='Nr aktu'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='data_chrztu',
            field=models.DateField(blank=True, help_text='Pełna data (dzień-miesiąc-rok), jeśli znana.', null=True, verbose_name='Data chrztu (pełna)'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='rok',
            field=models.PositiveIntegerField(help_text='Rok księgi chrztów (np. 2025).', verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='rok_chrztu',
            field=models.PositiveIntegerField(blank=True, help_text='Wpisz tylko rok, jeśli nie znasz pełnej daty chrztu.', null=True, verbose_name='Rok chrztu'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='rok_urodzenia',
            field=models.PositiveIntegerField(blank=True, help_text='Wpisz tylko rok, jeśli nie znasz dokładnej daty urodzenia.', null=True, verbose_name='Rok urodzenia (jeśli brak pełnej daty)'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='skan_aktu',
            field=models.FileField(blank=True, help_text='Opcjonalnie: załącz skan aktu (PDF, JPG).', null=True, upload_to='skany/chrzty/', verbose_name='Skan aktu'),
        ),
        migrations.AlterField(
            model_name='malzenstwo',
            name='data_slubu',
            field=models.DateField(blank=True, help_text='Pełna data (dzień-miesiąc-rok).', null=True, verbose_name='Data ślubu (pełna)'),
        ),
        migrations.AlterField(
            model_name='namaszczeniechorych',
            name='miejsce',
            field=models.CharField(blank=True, help_text='Np. dom chorego, szpital.', max_length=200, verbose_name='Miejsce'),
        ),
        migrations.AlterField(
            model_name='pierwszakomunia',
            name='parafia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='komunie', to='slowniki.parafia', verbose_name='Parafia I Komunii św.'),
        ),
        migrations.AlterField(
            model_name='pierwszakomunia',
            name='rok',
            field=models.CharField(blank=True, help_text='Np. 1998.', max_length=10, verbose_name='Rok I Komunii'),
        ),
        migrations.AlterField(
            model_name='zgon',
            name='akt_nr',
            field=models.CharField(blank=True, help_text='Numer aktu w księdze zgonów.', max_length=20, verbose_name='Nr aktu zgonu'),
        ),
        migrations.AlterField(
            model_name='zgon',
            name='rok',
            field=models.CharField(blank=True, help_text='Np. 2024.', max_length=10, verbose_name='Rok zgonu / księgi'),
        ),
    ]
