# Generated by Django 5.0.14 on 2025-11-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0002_remove_chrzest_cel_wydania_swiadectwa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chrzest',
            name='szafarz',
        ),
        migrations.AddField(
            model_name='chrzest',
            name='matka_wyznanie',
            field=models.CharField(blank=True, max_length=200, verbose_name='Matka - wyznanie'),
        ),
        migrations.AddField(
            model_name='chrzest',
            name='nazwisko_matki_rodowe',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nazwisko rodowe matki'),
        ),
        migrations.AddField(
            model_name='chrzest',
            name='ojciec_wyznanie',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ojciec - wyznanie'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='matka',
            field=models.CharField(blank=True, max_length=200, verbose_name='Matka (imię i nazwisko)'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='ojciec',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ojciec (imię i nazwisko)'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='rok_chrztu',
            field=models.PositiveIntegerField(blank=True, help_text='Wpisz tylko rok, jeśli nie znasz pełnej daty chrztu', null=True, verbose_name='Rok chrztu (jeśli brak pełnej daty)'),
        ),
    ]
