# Generated by Django 5.0.14 on 2026-01-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0002_remove_chrzest_sakramenty__rok_d6a118_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bierzmowanie',
            name='akt_nr',
            field=models.CharField(blank=True, help_text='Numer aktu bierzmowania; jeśli nie podasz, może zostać wypełniony automatycznie.', max_length=5, verbose_name='Nr aktu bierzmowania'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='imie_bierzmowania',
            field=models.CharField(blank=True, help_text='Imię przyjęte przy bierzmowaniu.', max_length=30, verbose_name='Imię bierzmowania'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='miejsce_bierzmowania',
            field=models.CharField(blank=True, max_length=30, verbose_name='Miejsce bierzmowania'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='parafia_nazwa_reczna',
            field=models.CharField(blank=True, help_text='Jeśli nie ma na liście powyżej.', max_length=50, verbose_name='Parafia (opis ręczny)'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='rok',
            field=models.CharField(blank=True, help_text='Np. 2005.', max_length=5, verbose_name='Rok bierzmowania'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='swiadek',
            field=models.CharField(blank=True, help_text='Imię i nazwisko świadka.', max_length=30, verbose_name='Świadek bierzmowania'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='szafarz_opis_reczny',
            field=models.CharField(blank=True, help_text='Np. „bp Jan Kowalski”, „ks. Piotr Nowak”.', max_length=30, verbose_name='Szafarz (opis ręczny)'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='akt_nr',
            field=models.CharField(help_text='Numer aktu chrztu w danym roku; jeśli nie podasz, wypełni się automatycznie.', max_length=5, verbose_name='Nr aktu'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='matka',
            field=models.CharField(blank=True, max_length=30, verbose_name='Matka (imię i nazwisko)'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='miejsce_chrztu',
            field=models.CharField(blank=True, max_length=30, verbose_name='Miejsce chrztu'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='miejsce_urodzenia',
            field=models.CharField(blank=True, max_length=30, verbose_name='Miejsce urodzenia'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='nazwisko_matki_rodowe',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nazwisko rodowe matki'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='ojciec',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ojciec (imię i nazwisko)'),
        ),
        migrations.AlterField(
            model_name='malzenstwo',
            name='akt_nr',
            field=models.CharField(blank=True, help_text='Numer aktu w księdze małżeństw.', max_length=5, verbose_name='Nr aktu małżeństwa'),
        ),
        migrations.AlterField(
            model_name='malzenstwo',
            name='parafia_opis_reczny',
            field=models.CharField(blank=True, help_text='Jeśli nie ma parafii na liście powyżej, wpisz tutaj.', max_length=50, verbose_name='Parafia ślubu (opis ręczny)'),
        ),
        migrations.AlterField(
            model_name='malzenstwo',
            name='rok',
            field=models.CharField(blank=True, help_text='Np. 2014. Możesz wpisać tylko rok.', max_length=5, verbose_name='Rok ślubu'),
        ),
        migrations.AlterField(
            model_name='malzenstwo',
            name='swiadek_a',
            field=models.CharField(blank=True, max_length=30, verbose_name='Świadek A'),
        ),
        migrations.AlterField(
            model_name='malzenstwo',
            name='swiadek_b',
            field=models.CharField(blank=True, max_length=230, verbose_name='Świadek B'),
        ),
        migrations.AlterField(
            model_name='malzenstwo',
            name='swiadek_urzedowy_opis_reczny',
            field=models.CharField(blank=True, help_text='Kapłan/diakon, który asystował przy zawarciu małżeństwa.', max_length=30, verbose_name='Świadek urzędowy / asystujący (opis ręczny)'),
        ),
        migrations.AlterField(
            model_name='namaszczeniechorych',
            name='miejsce',
            field=models.CharField(blank=True, help_text='Np. dom chorego, szpital.', max_length=30, verbose_name='Miejsce'),
        ),
        migrations.AlterField(
            model_name='pierwszakomunia',
            name='rok',
            field=models.CharField(blank=True, help_text='Np. 1998.', max_length=5, verbose_name='Rok I Komunii'),
        ),
        migrations.AlterField(
            model_name='zgon',
            name='akt_nr',
            field=models.CharField(blank=True, help_text='Numer aktu w księdze zgonów.', max_length=5, verbose_name='Nr aktu zgonu'),
        ),
        migrations.AlterField(
            model_name='zgon',
            name='cmentarz',
            field=models.CharField(blank=True, max_length=30, verbose_name='Cmentarz'),
        ),
        migrations.AlterField(
            model_name='zgon',
            name='miejsce_zgonu',
            field=models.CharField(blank=True, max_length=30, verbose_name='Miejsce zgonu'),
        ),
        migrations.AlterField(
            model_name='zgon',
            name='rok',
            field=models.CharField(blank=True, help_text='Np. 2024.', max_length=5, verbose_name='Rok zgonu / księgi'),
        ),
    ]
