# Generated by Django 5.0.14 on 2025-12-01 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmentarz', '0001_initial'),
        ('sakramenty', '0002_alter_bierzmowanie_akt_nr_alter_chrzest_akt_nr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgon',
            name='grob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pochowki', to='cmentarz.grob', verbose_name='Grób'),
        ),
    ]
