# Generated by Django 5.0.14 on 2025-11-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0002_chrzest_skan_aktu'),
    ]

    operations = [
        migrations.AddField(
            model_name='malzenstwo',
            name='skan_aktu',
            field=models.FileField(blank=True, null=True, upload_to='skany/malzenstwa/', verbose_name='Skan aktu/protokołu'),
        ),
    ]
