# Generated by Django 5.0.14 on 2025-12-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmentarz', '0002_sektor_alter_grob_options_grob_data_oplaty_and_more'),
        ('sakramenty', '0003_zgon_grob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgon',
            name='grob',
            field=models.ForeignKey(blank=True, help_text='Grób, w którym pochowano zmarłego (jeśli dotyczy).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pochowki', to='cmentarz.grob', verbose_name='Grób'),
        ),
    ]
