# Generated by Django 5.0.14 on 2025-11-02 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0002_osoba_imie_bierzmowania'),
        ('sakramenty', '0003_remove_chrzest_szafarz_chrzest_matka_wyznanie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrzest',
            name='ochrzczony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chrzty', to='osoby.osoba', verbose_name='Ochrzczony/a'),
        ),
    ]
