# Generated by Django 5.0.14 on 2025-11-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0003_malzenstwo_skan_aktu'),
    ]

    operations = [
        migrations.AddField(
            model_name='bierzmowanie',
            name='skan_aktu',
            field=models.FileField(blank=True, null=True, upload_to='skany/bierzmowania/', verbose_name='Skan świadectwa/aktu'),
        ),
    ]
