# Generated by Django 5.0.14 on 2025-11-02 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0002_osoba_imie_bierzmowania'),
        ('sakramenty', '0004_alter_chrzest_ochrzczony'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bierzmowanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.CharField(blank=True, help_text='Np. 2005', max_length=10, verbose_name='Rok bierzmowania')),
                ('akt_nr', models.CharField(blank=True, help_text='Numer aktu w księdze bierzmowania', max_length=20, verbose_name='Nr aktu bierzmowania')),
                ('parafia', models.CharField(blank=True, max_length=200, verbose_name='Parafia bierzmowania')),
                ('szafarz', models.CharField(blank=True, help_text='Np. bp Jan Kowalski', max_length=200, verbose_name='Szafarz (udzielający bierzmowania)')),
                ('swiadek', models.CharField(blank=True, help_text='Imię i nazwisko świadka, bez daty urodzenia', max_length=200, verbose_name='Świadek bierzmowania')),
                ('uwagi_wew', models.TextField(blank=True, verbose_name='Uwagi kancelaryjne (wewnętrzne)')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bierzmowania', to='osoby.osoba', verbose_name='Osoba')),
            ],
            options={
                'verbose_name': 'Bierzmowanie',
                'verbose_name_plural': 'Bierzmowania',
                'ordering': ['rok', 'osoba__nazwisko', 'osoba__imie_pierwsze'],
            },
        ),
        migrations.CreateModel(
            name='Malzenstwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.CharField(blank=True, help_text='Np. 2010', max_length=10, verbose_name='Rok ślubu')),
                ('akt_nr', models.CharField(blank=True, help_text='Numer aktu w księdze małżeństw', max_length=20, verbose_name='Nr aktu małżeństwa')),
                ('parafia', models.CharField(blank=True, max_length=200, verbose_name='Parafia ślubu')),
                ('swiadek_urzedowy', models.CharField(blank=True, help_text='Kapłan/diakon asystujący przy zawarciu małżeństwa', max_length=200, verbose_name='Świadek urzędowy / asystujący')),
                ('uwagi_wew', models.TextField(blank=True, verbose_name='Uwagi kancelaryjne (wewnętrzne)')),
                ('malzonek_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malzenstwa_jako_a', to='osoby.osoba', verbose_name='Małżonek A')),
                ('malzonek_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malzenstwa_jako_b', to='osoby.osoba', verbose_name='Małżonek B')),
            ],
            options={
                'verbose_name': 'Małżeństwo',
                'verbose_name_plural': 'Małżeństwa',
                'ordering': ['rok', 'akt_nr'],
            },
        ),
        migrations.CreateModel(
            name='NamaszczenieChorych',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data posługi')),
                ('miejsce', models.CharField(blank=True, help_text='Np. dom chorego, szpital', max_length=200, verbose_name='Miejsce')),
                ('szafarz', models.CharField(blank=True, help_text='Kto udzielił sakramentów / posługi', max_length=200, verbose_name='Szafarz')),
                ('spowiedz', models.BooleanField(default=False, verbose_name='Spowiedź')),
                ('komunia', models.BooleanField(default=False, verbose_name='Komunia święta')),
                ('namaszczenie', models.BooleanField(default=False, verbose_name='Namaszczenie chorych')),
                ('uwagi_wew', models.TextField(blank=True, verbose_name='Uwagi duszpasterskie / stan chorego')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namaszczenia', to='osoby.osoba', verbose_name='Osoba')),
            ],
            options={
                'verbose_name': 'Namaszczenie chorych / posługa',
                'verbose_name_plural': 'Namaszczenia chorych / posługi',
                'ordering': ['-data', 'osoba__nazwisko', 'osoba__imie_pierwsze'],
            },
        ),
        migrations.CreateModel(
            name='PierwszaKomunia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.CharField(blank=True, help_text='Np. 1998', max_length=10, verbose_name='Rok I Komunii')),
                ('parafia', models.CharField(blank=True, help_text='Miejsce przyjęcia I Komunii', max_length=200, verbose_name='Parafia')),
                ('uwagi_wew', models.TextField(blank=True, verbose_name='Uwagi kancelaryjne (wewnętrzne)')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komunie', to='osoby.osoba', verbose_name='Osoba')),
            ],
            options={
                'verbose_name': 'I Komunia Święta',
                'verbose_name_plural': 'I Komunie Święte',
                'ordering': ['rok', 'osoba__nazwisko', 'osoba__imie_pierwsze'],
            },
        ),
        migrations.CreateModel(
            name='Zgon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.CharField(blank=True, help_text='Np. 2024', max_length=10, verbose_name='Rok zgonu / księgi')),
                ('akt_nr', models.CharField(blank=True, help_text='Numer aktu w księdze zgonów', max_length=20, verbose_name='Nr aktu zgonu')),
                ('data_zgonu', models.DateField(blank=True, null=True, verbose_name='Data zgonu')),
                ('miejsce_zgonu', models.CharField(blank=True, max_length=200, verbose_name='Miejsce zgonu')),
                ('data_pogrzebu', models.DateField(blank=True, null=True, verbose_name='Data pogrzebu')),
                ('cmentarz', models.CharField(blank=True, max_length=200, verbose_name='Cmentarz')),
                ('uwagi_wew', models.TextField(blank=True, verbose_name='Uwagi kancelaryjne (wewnętrzne)')),
                ('osoba', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zgon', to='osoby.osoba', verbose_name='Zmarły/a')),
            ],
            options={
                'verbose_name': 'Zgon',
                'verbose_name_plural': 'Zgony',
                'ordering': ['rok', 'akt_nr'],
            },
        ),
    ]
