# Generated by Django 5.0.14 on 2025-11-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0005_bierzmowanie_malzenstwo_namaszczeniechorych_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bierzmowanie',
            name='data_bierzmowania',
            field=models.DateField(blank=True, help_text='Pełna data bierzmowania (dzień-miesiąc-rok), jeśli znana', null=True, verbose_name='Data bierzmowania (pełna)'),
        ),
    ]
