# Generated by Django 5.0.14 on 2025-11-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0006_bierzmowanie_data_bierzmowania'),
    ]

    operations = [
        migrations.AddField(
            model_name='malzenstwo',
            name='data_slubu',
            field=models.DateField(blank=True, help_text='Pełna data ślubu (dzień-miesiąc-rok)', null=True, verbose_name='Data ślubu'),
        ),
    ]
