# Generated by Django 5.0.14 on 2025-11-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0007_malzenstwo_data_slubu'),
        ('slowniki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bierzmowanie',
            name='parafia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bierzmowania', to='slowniki.parafia', verbose_name='Parafia bierzmowania'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='szafarz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bierzmowania_udzielone', to='slowniki.duchowny', verbose_name='Szafarz bierzmowania'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='matka_wyznanie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matki_przy_chrzcie', to='slowniki.wyznanie', verbose_name='Matka - wyznanie'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='ojciec_wyznanie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ojcowie_przy_chrzcie', to='slowniki.wyznanie', verbose_name='Ojciec - wyznanie'),
        ),
        migrations.AlterField(
            model_name='namaszczeniechorych',
            name='szafarz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='namaszczenia_udzielone', to='slowniki.duchowny', verbose_name='Szafarz'),
        ),
    ]
