# Generated by Django 5.0.14 on 2025-11-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0008_alter_bierzmowanie_parafia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malzenstwo',
            old_name='swiadek_urzedowy',
            new_name='asystujacy',
        ),
        migrations.RenameField(
            model_name='malzenstwo',
            old_name='parafia',
            new_name='parafia_slubu',
        ),
    ]
