# Generated by Django 5.0.14 on 2025-11-02 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0009_rename_swiadek_urzedowy_malzenstwo_asystujacy_and_more'),
        ('slowniki', '0004_wyznanie_aktywne'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='malzenstwo',
            options={'ordering': ['rok', 'malzonek_a__nazwisko', 'malzonek_b__nazwisko'], 'verbose_name': 'Małżeństwo', 'verbose_name_plural': 'Małżeństwa'},
        ),
        migrations.RemoveField(
            model_name='malzenstwo',
            name='asystujacy',
        ),
        migrations.RemoveField(
            model_name='malzenstwo',
            name='parafia_slubu',
        ),
        migrations.AddField(
            model_name='bierzmowanie',
            name='imie_bierzmowania',
            field=models.CharField(blank=True, help_text='Imię przyjęte przy bierzmowaniu', max_length=100, verbose_name='Imię bierzmowania'),
        ),
        migrations.AddField(
            model_name='bierzmowanie',
            name='parafia_nazwa_reczna',
            field=models.CharField(blank=True, help_text='Jeśli nie ma na liście powyżej', max_length=200, verbose_name='Parafia (opis ręczny)'),
        ),
        migrations.AddField(
            model_name='bierzmowanie',
            name='szafarz_opis_reczny',
            field=models.CharField(blank=True, help_text='Np. «bp Jan Kowalski», «ks. Piotr Nowak»', max_length=200, verbose_name='Szafarz (opis ręczny)'),
        ),
        migrations.AddField(
            model_name='malzenstwo',
            name='parafia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sluby', to='slowniki.parafia', verbose_name='Parafia ślubu'),
        ),
        migrations.AddField(
            model_name='malzenstwo',
            name='parafia_opis_reczny',
            field=models.CharField(blank=True, help_text='Jeśli nie ma parafii na liście powyżej, wpisz tutaj.', max_length=200, verbose_name='Parafia ślubu (opis ręczny)'),
        ),
        migrations.AddField(
            model_name='malzenstwo',
            name='swiadek_urzedowy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sluby_asystowane', to='slowniki.duchowny', verbose_name='Świadek urzędowy / asystujący'),
        ),
        migrations.AddField(
            model_name='malzenstwo',
            name='swiadek_urzedowy_opis_reczny',
            field=models.CharField(blank=True, help_text='Kapłan/diakon, który asystował przy zawarciu małżeństwa.', max_length=200, verbose_name='Świadek urzędowy / asystujący (opis ręczny)'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='data_bierzmowania',
            field=models.DateField(blank=True, help_text='Pełna data (dzień-miesiąc-rok), jeśli znana', null=True, verbose_name='Data bierzmowania (pełna)'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='swiadek',
            field=models.CharField(blank=True, help_text='Imię i nazwisko świadka (bez daty urodzenia)', max_length=200, verbose_name='Świadek bierzmowania'),
        ),
        migrations.AlterField(
            model_name='bierzmowanie',
            name='szafarz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bierzmowania', to='slowniki.duchowny', verbose_name='Szafarz (udzielający bierzmowania)'),
        ),
        migrations.AlterField(
            model_name='malzenstwo',
            name='akt_nr',
            field=models.CharField(blank=True, help_text='Numer aktu w księdze małżeństw.', max_length=30, verbose_name='Nr aktu małżeństwa'),
        ),
        migrations.AlterField(
            model_name='malzenstwo',
            name='data_slubu',
            field=models.DateField(blank=True, null=True, verbose_name='Data ślubu (pełna)'),
        ),
        migrations.AlterField(
            model_name='malzenstwo',
            name='rok',
            field=models.CharField(blank=True, help_text='Np. 2014. Możesz wpisać tylko rok.', max_length=10, verbose_name='Rok ślubu'),
        ),
        migrations.AlterField(
            model_name='malzenstwo',
            name='uwagi_wew',
            field=models.TextField(blank=True, verbose_name='Uwagi (wewnętrzne)'),
        ),
    ]
