# Generated by Django 5.0.14 on 2025-11-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0005_alter_osoba_wyznanie'),
        ('sakramenty', '0010_alter_malzenstwo_options_and_more'),
        ('slowniki', '0004_wyznanie_aktywne'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bierzmowanie',
            constraint=models.UniqueConstraint(fields=('osoba',), name='unique_bierzmowanie_per_osoba'),
        ),
        migrations.AddConstraint(
            model_name='chrzest',
            constraint=models.UniqueConstraint(fields=('ochrzczony',), name='unique_chrzest_per_osoba'),
        ),
        migrations.AddConstraint(
            model_name='chrzest',
            constraint=models.UniqueConstraint(fields=('rok', 'akt_nr'), name='unique_chrzest_rok_akt'),
        ),
        migrations.AddConstraint(
            model_name='malzenstwo',
            constraint=models.UniqueConstraint(fields=('rok', 'akt_nr'), name='unique_malzenstwo_rok_akt'),
        ),
        migrations.AddConstraint(
            model_name='pierwszakomunia',
            constraint=models.UniqueConstraint(fields=('osoba',), name='unique_komunia_per_osoba'),
        ),
        migrations.AddConstraint(
            model_name='zgon',
            constraint=models.UniqueConstraint(fields=('osoba',), name='unique_zgon_per_osoba'),
        ),
        migrations.AddConstraint(
            model_name='zgon',
            constraint=models.UniqueConstraint(fields=('rok', 'akt_nr'), name='unique_zgon_rok_akt'),
        ),
    ]
