# Generated by Django 5.0.14 on 2025-11-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0011_bierzmowanie_unique_bierzmowanie_per_osoba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrzest',
            name='miejsce_chrztu',
            field=models.CharField(blank=True, max_length=200, verbose_name='Miejsce chrztu'),
        ),
    ]
