# Generated by Django 5.0.14 on 2025-11-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0012_alter_chrzest_miejsce_chrztu'),
        ('slowniki', '0004_wyznanie_aktywne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pierwszakomunia',
            name='parafia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='komuni', to='slowniki.parafia', verbose_name='Parafia I komuni św.'),
        ),
    ]
