# Generated by Django 5.0.14 on 2025-11-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0015_alter_namaszczeniechorych_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bierzmowanie',
            name='swiadek',
            field=models.CharField(blank=True, help_text='Imię i nazwisko świadka', max_length=200, verbose_name='Świadek bierzmowania'),
        ),
    ]
