# Generated by Django 5.0.14 on 2025-11-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0016_alter_bierzmowanie_swiadek'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namaszczeniechorych',
            options={'ordering': ['data_poslugi', 'osoba__nazwisko', 'osoba__imie_pierwsze'], 'verbose_name': 'Namaszczenie chorych / posługa', 'verbose_name_plural': 'Namaszczenia chorych / posługi'},
        ),
        migrations.RenameField(
            model_name='namaszczeniechorych',
            old_name='data',
            new_name='data_poslugi',
        ),
    ]
