# Generated by Django 5.0.14 on 2025-11-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0018_alter_namaszczeniechorych_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bierzmowanie',
            name='data_bierzmowania',
            field=models.DateField(blank=True, help_text='Pełna data (dzień-miesiąc-rok)', null=True, verbose_name='Data bierzmowania (pełna)'),
        ),
        migrations.AlterField(
            model_name='chrzest',
            name='rok_chrztu',
            field=models.PositiveIntegerField(blank=True, help_text='Wpisz tylko rok, jeśli nie znasz pełnej daty chrztu', null=True, verbose_name='Rok chrztu'),
        ),
    ]
