# Generated by Django 5.0.14 on 2025-11-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0019_alter_bierzmowanie_data_bierzmowania_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bierzmowanie',
            name='miejsce_bierzmowania',
            field=models.CharField(blank=True, help_text='Miejsce bierzmowania', max_length=100, verbose_name='Miejsce bierzmowania'),
        ),
    ]
