# Generated by Django 5.0.14 on 2025-11-15 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0020_bierzmowanie_miejsce_bierzmowania'),
        ('slowniki', '0005_alter_duchowny_tytul'),
    ]

    operations = [
        migrations.AddField(
            model_name='chrzest',
            name='parafia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chrzty', to='slowniki.parafia', verbose_name='Parafia chrztu'),
        ),
    ]
