# Generated by Django 5.0.14 on 2025-11-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenty', '0021_chrzest_parafia'),
    ]

    operations = [
        migrations.AddField(
            model_name='malzenstwo',
            name='swiadek_a',
            field=models.CharField(blank=True, max_length=200, verbose_name='Świadek A (np. małżonka)'),
        ),
        migrations.AddField(
            model_name='malzenstwo',
            name='swiadek_b',
            field=models.CharField(blank=True, max_length=200, verbose_name='Świadek B (np. małżonka)'),
        ),
    ]
